Tests for `CatTargetDriftAnalyzer`
evidentlyai/evidently pull request #94
Opened 2021-12-08 18:38 UTC by burkovae

- [ ] Add tests for `CatTargetDriftAnalyzer`
- [ ] Refactor
- [ ] Ask a bunch of questions :-)

2021-12-09 11:27 UTC, burkovae commented
I suggest making `option_providers.get(...)` as a parameter of the `calculate` method itself. It makes the method better testable, readable, and more robust against changes. Please think about doing it for other analyzers as well.

(as mentioned in chat, deeply hidden `option_provides` that depend on reading `config.json` does make writing tests painful. To encourage testing, writing test should require minimal effort ✔)

2021-12-09 21:37 UTC, Liraim commented
> I suggest making `option_providers.get(...)` as a parameter of the `calculate` method itself. It makes the method better testable, readable, and more robust against changes. Please think about doing it for other analyzers as well.
> 

This is hard topic for discussion, because I personally don't like both options, but I will try to describe why I did so:

My first attempt for `options_provider` was like you describe, but at the moment it made signatures across all code (analyzers, tabs, widgets, etc) much heavier than I want it to be. So I put `options_provider` as public field in base classes. 

This solution make readability a bit harder (as you do not know that you need to mock this until you use it). But it doesn't affect testability as `options_provider` can be set after creating required object. For example:
```python
analyzer = DataDriftAnalyzer('')
options_provider = OptionsProvider()
options_provider.add(DataDriftOptions(confidence=0.5))
analyzer.options_provider = options_provider
analyzer.(reference_data, current_data, column_mapping)
```

Doesn't have much difference in testability (except readability) than:
```python
analyzer = DataDriftAnalyzer('')
options_provider = OptionsProvider()
options_provider.add(DataDriftOptions(confidence=0.5))
analyzer.(reference_data, current_data, column_mapping, options_provider)
```

_**But**_ because we have some other thoughts about changing of `calculate` method, so probably I will consider to move options_provider to arguments once more.

> (as mentioned in chat, deeply hidden `option_provides` that depend on reading `config.json` does make writing tests painful. To encourage testing, writing test should require minimal effort ✔)

This part is a bit confusing. `options_provider` doesn't depends on `config.json`. `config.json` is a configuration file for Evidently CLI (the way to run our library as console command). For using `Options` in scripts or notebooks you should manually create required `Options` (eg `DataDriftOptions`).

2021-12-09 21:57 UTC, Liraim requested changes

2021-12-10 00:22 UTC, burkovae commented
Awsome @Liraim , thanks for your review.

Let me just respond to you comments:

> This solution make readability a bit harder (as you do not know that you need to mock this until you use it). But it doesn't affect testability as options_provider can be set after creating required object. For example:

     analyzer = DataDriftAnalyzer('')
     options_provider = OptionsProvider()
     options_provider.add(DataDriftOptions(confidence=0.5))
     analyzer.options_provider = options_provider
     analyzer.(reference_data, current_data, column_mapping)

> Doesn't have much difference in testability (except readability) than:

     analyzer = DataDriftAnalyzer('')
     options_provider = OptionsProvider()
     options_provider.add(DataDriftOptions(confidence=0.5))
     analyzer.(reference_data, current_data, column_mapping, options_provider)

Both solutions are problematic **because** they require knowledge about the implementation details. Perhaps moving `options_provider` as a constructor argument of analyzer will at least make it obvious for a reader/contributer/tester like so

    class Analyzer:
		def __init__():
			self.options_provider = OptionsProvider()
				
	    ...

	class CatTargetDriftAnalyzer(Analyzer):
		def __init__(options=None):
		    super().__init__()
			if options is None:
				options = DataDriftOptions(confidence=0.5)
			self.options_provider.add(options)
					
	    ...
		
But also something like this may help as well:

	class CatTargetDriftAnalyzer(Analyzer):
		def __init__(options=None):
			if options is None:
				options = DataDriftOptions(confidence=0.5)
			options_provider = OptionsProvider.get_instance().add(options)
					
	    ...

In such way, a user of this class will know that options exist in the context. I think a solution can be drafted in another PR. Thanks four sharing your thought.

2021-12-10 00:48 UTC, burkovae commented on evidently/analyzers/cat_target_drift_analyzer.py
> +                  column_mapping: ColumnMapping, options: DataDriftOptions = None) -> dict:
Mh... well it didn't break any code 🤔 (and smoke tests).

That would be an excellent test case. Can you add one in another PR?

2021-12-10 00:49 UTC, burkovae commented on evidently/analyzers/cat_target_drift_analyzer.py
> +# TODO: document somewhere, that all analyzers are mutators, i.e. they will change
I removed TODO keywords and moved the comment to the culprit. When you takle it in another PR at some point, we can safely remove the comment then. ✔

2021-12-10 00:49 UTC, burkovae commented on evidently/analyzers/cat_target_drift_analyzer.py
> +        # TODO: consider replacing only values in target and prediction column, see comment above
dito ✔

2021-12-10 00:49 UTC, burkovae commented on evidently/analyzers/cat_target_drift_analyzer.py
> +from ..options import DataDriftOptions
Done ✔

2021-12-10 00:50 UTC, burkovae commented on evidently/analyzers/cat_target_drift_analyzer.py
> +                  column_mapping: ColumnMapping, options: DataDriftOptions = None) -> dict:
btw: i used your suggestions above in the tests. As you said `options` are something beyond the scope of this PR.

2021-12-10 11:53 UTC, Liraim commented on evidently/analyzers/cat_target_drift_analyzer.py
> +                  column_mapping: ColumnMapping, options: DataDriftOptions = None) -> dict:
Yes, this won't break code execution, but will break options passing through hierarchy of components. Unfortunately, there are no test for that yet (I'm planning to add it as soon as can).

2021-12-10 11:56 UTC, Liraim approved these changes
Looks good now.

2021-12-10 14:55 UTC, Liraim commented
> I have a quetion: It seems to me that you never use `prediction_type` or `target_type`:
> ![image](https://user-images.githubusercontent.com/15078122/145265606-092aa227-f57e-41ae-8be6-de6fc9cea7bc.png)

As far as I know, this fields aren't used in Widgets directly, but they are returned as fields in `Sections` in JSON-format (so it can be used outside of our code base). So I won't recommend to delete it until required by some strong reasons.

2021-12-10 16:45 UTC, burkovae commented
@Liraim , with reference to [a SO question](https://stackoverflow.com/a/15700228/1256837) I believe you can get rid of code that you actually don't use yourself.
1. right now evidently is under active development - which is awesome - and I think you can allow yourself to "break" things to be more efficient with the code base.
2. If things break, there is always an issue tracker :D ... and you actually get to know the users and their use-cases - in particular, why they need such a feature (which you can pack in a test case again 🤩)

Whatever decision you reach, I think in the long run, when you [focus on the core features](https://ben.balter.com/2016/07/21/removing-a-feature-is-a-feature/) you'll deliver more value faster. But that's just my 2 cents. 

Thank you!

2021-12-10 16:47 UTC, burkovae commented
I think that's it for this PR. Happy to help out and thanks for the discussion and feeback!

2021-12-10 16:52 UTC, Liraim commented
> @Liraim , with reference to [a SO question](https://stackoverflow.com/a/15700228/1256837) I believe you can get rid of code that you actually don't use yourself.
> 
> 1. right now evidently is under active development - which is awesome - and I think you can allow yourself to "break" things to be more efficient with the code base.
> 2. If things break, there is always an issue tracker :D ... and you actually get to know the users and their use-cases - in particular, why they need such a feature (which you can pack in a test case again 🤩)
> 

I'm agree with this arguments, and we trying to delete all dead code.
And about subject - I will investigate usage of this field, and probably will remove, but I don't want to stale PR because it can take some time to check.

2021-12-10 16:53 UTC, merged