Tests for `NumTargetDriftAnalyzer`
evidentlyai/evidently pull request #97
Opened 2021-12-11 10:49 UTC by burkovae

- [ ] Write test for current behavior
- [ ] Refactor and simplify code
  - [ ]   When target column is categorical, we raise a `ValueError` with explanation instead a cryptic one
- [ ] Ask a bunch of questions
  - [ ] Any suggestion what we should do about ` test_computing_of_correlations_between_columns_fails_for_second_data_when_columns_missing` ? (the second data is missing numerical feature from the first one). Should we handle it gracefully or raise a `ValueError`
  - [ ] Any suggestion what we should do about  `test_computing_of_correlations_between_columns_fails_for_second_data_when_columns_missing_2` (column names do mismatch in both datasets). Should we handle it gracefully or raise a `ValueError`

2021-12-15 22:33 UTC, Liraim commented
Both cases: `test_computing_of_correlations_between_columns_fails_for_second_data_when_columns_missing` and `test_computing_of_correlations_between_columns_fails_for_second_data_when_columns_missing_2` ideally should raise some specific error about data format mismatch (eg, missing required columns, mismatch feature columns etc).

Currently it wasn't implemented (but we're planning to add such checks in future).

For now I would suggest to add generic 'test should rise some error' assertion for this tests.

2021-12-26 14:01 UTC, Liraim requested changes

2021-12-27 12:40 UTC, burkovae commented on evidently/analyzers/num_target_drift_analyzer.py
> +        result['metrics'] = dict(**result['metrics'], **target_metrics, **prediction_metrics)
yes, good spotting!

2021-12-27 12:41 UTC, burkovae commented on evidently/analyzers/num_target_drift_analyzer.py
> +def _compute_correlation(reference_data: pd.DataFrame, current_data: pd.DataFrame, prefix,
you mean for other parameters?

2021-12-27 12:41 UTC, burkovae commented on evidently/analyzers/test_numerical_target_drift_analyzer.py
> +    assert correlations['current'], {'another_target': 1.0}
Awesome! Yes, that was a typo!

2021-12-27 12:47 UTC, Liraim commented on evidently/analyzers/num_target_drift_analyzer.py
> +def _compute_correlation(reference_data: pd.DataFrame, current_data: pd.DataFrame, prefix,
Yes, exactly.

2021-12-27 12:48 UTC, Liraim approved these changes
Looks good now.

2021-12-27 19:35 UTC, merged